### ISSUE TITLE
Paper is getting out of whack, technically

### ISSUE THREAD

**Issue by gavinsimpson** [SimonGoring/neotoma_paper#14]
We need to give the paper a clean up as various changes are breaking functionality or introducing issues. Two that I am currently aware of are:

 1. There are **two** code chunks that change the way **knitr** operates.
     * the one starting on [Line 15](https://github.com/SimonGoring/neotoma_paper/blob/master/Neotoma_paper.Rmd#L15), which is the main options chunk
     * the one starting on [Line 152](https://github.com/SimonGoring/neotoma_paper/blob/master/Neotoma_paper.Rmd#L152), which introduces some of @karthik's (KR?) defaults.

     We need to reconcile these into a single settings chunk at the start of the paper.

 2. Something has broken the `Makefile`, and I suspect it is that somewhere along the line `library("knitr")` has gotten removed from the paper. Now, it shouldn't be there as you don't need it to follow the **neotoma** examples but only to build the `.Rmd`. However, the `Makefile` breaks because it doesn't load **knitr** and the paper was written (currently) assuming **knitr** was loaded and attached to the search path.

    We could add `library("knitr")` to the `Makefile` `Rscript` invocations, or we could, I presume change `kable()` into `knitr::kable()` through the paper. The former is most explicit.

A third issue is how we build the paper. It seems that we have two options currently:

 * `knit()` by hand which is what I had to do to check that I'd not screwed up naming the code chunks, or
 * Use the `Makefile`

A disadvantage of the latter is that it doesn't generate intermediate files (at the moment --- though I suppose we can get it to do that). It is important to have a rendered `.md` and associated images in `figures/` if we want people to take our `.Rmd` source and work with it because **rmarkdown** is not yet available on CRAN and users, especially those on Windows, will have to jump through extra hoops to work with these sources.

@karthik or @sckott could you comment on how you envisage these papers being built as I understand you are trialling some pan-rOpensci approaches to this which are in use here?

**Comment by SimonGoring** [comment]
Hi @gavinsimpson and @karthik I assume this issue is closed now.  Can you confirm?

**Comment by karthik** [comment]
Yeah, fine with me.

**Comment by gavinsimpson** [comment]
@SimonGoring Yep, between us we got all those niggling issues ironed out before the initial submission.
