### ISSUE TITLE
Getting code block to be nicely formatted in html and docx?

### ISSUE THREAD

**Issue by andydawson** [SimonGoring/neotoma_paper#20]
Is there an automated way to get the code blocks in the html file to be formatted nicely as they are in R? Code formatting (spacing mostly) looks messy in html and docx files.

**Comment by SimonGoring** [comment]
I'm closing this issue.  I think things look okay now.  @andydawson is free to re-open, but only until the paper is re-submitted. :)

**Comment by gavinsimpson** [comment]
Also, do we care? We can render a PDF which looks much nicer and the journal will (or can be asked to) render the code blocks in a monospace font when we get whatever passes for proofs at Open Quaternary.
