### ISSUE TITLE
Refs missing capitalization and other minor formatting issues

### ISSUE THREAD

**Issue by andydawson** [SimonGoring/neotoma_paper#32]
Some of the refs were missing capitalization on proper names. I fixed them in the bib file, but I'm not sure how to recompile without knitting, and I can't get pander installed so haven't checked them. I'm trying to figure it out now, but wanted to let @Simon and others know before submitting!

**Comment by SimonGoring** [comment]
I've gone through the references and protected the capitalization in commit 057fa13700172159ae0ebf88b19b670d81305df4.
